### ISSUE TITLE
Spike: Find out how to rebuild automatically

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/gatsby-starter-kontent#10]
### Expected result

Gatsby's store is rebuilt upon bootstrap (`npm run develop`, `npm run deploy`). Find out:

* whether there have to be provisions made in the source code of either an app, or a plugin, to rebuild the store automatically
* or, if only the automated CLI commands in the hosting environment can make the automatic rebuilds

### Resources

* https://github.com/justinwhall/gatsby-wordpress-netlify-starter
* https://www.netlify.com/docs/api/
* https://github.com/gatsbyjs/gatsby/issues/4202
* https://github.com/gatsbyjs/gatsby/issues/2753
* https://github.com/danielmahon/gatsby-starter-procyon

**Comment by CollierCZ** [comment]
With Netlify, you can use webhooks to trigger rebuilds: https://www.netlify.com/docs/webhooks/ So a change to content in Kentico Cloud can trigger a rebuild.

**Comment by JanLenoch** [comment]
> With Netlify, you can use webhooks to trigger rebuilds: https://www.netlify.com/docs/webhooks/ So a change to content in Kentico Cloud can trigger a rebuild.

Exactly, that's why I've added the link to https://www.netlify.com/docs/api/ to the description. But, we'd like to not be limited to just Netlify. The ideal result of this spike would be a set of carefully distilled wiki pages (with a howto). Each page per provider (that supports webhook-initiated-CLI).

**Comment by CollierCZ** [comment]
Can you provide a list of providers you'd like covered? Or is it about finding providers which support that?

**Comment by Abdulhakimsg** [comment]
Hi , deployment on AWS for gatsby + wordpress would be greatly appreciated. I am expected to use AWS and not netlify.Anyone has got it figured out?

**Comment by petrsvihlik** [comment]
@rshackleton that would be great. feel free to use the [wiki](https://github.com/Kentico/gatsby-starter-kentico-cloud/wiki).

**Comment by Abdulhakimsg** [comment]
@rshackleton can't wait!
