### ISSUE TITLE
Dump content and models via Content Management API into the repo

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/gatsby-starter-kontent#7]
### Motivation

Those who clone this repo can only guess what the content models and items in the KK project are.

### Design guidelines

Dump the entire content project into JSON files so that everyone can clone the project.

**Comment by Simply007** [comment]
fixed in https://github.com/Kentico/gatsby-starter-kontent/commit/0864d97b51ce705bd9471ec1b512d56dfbd418ee#diff-7a53765b8babef679e3e43dfcb8b12dbb8ed562e1b343935d53b42443403fb7e
